[package]
name = "reply-to-me"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
futures = "0.1"
reqwest = { version = "0.10", features = ["blocking", "json"] }
telebot = "0.3.1"
